server:
  port: 8002
  #Address: 192.168.1.99

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.0.223:2001/eureka
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka/,http://localhost:7003/eureka/

  instance:
    instance-id: dhccczhyq
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: dhccczhyq
  company.name: www.dhcc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: dhccczhyq
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.141:3306/dhcplat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    properties:
      hibernate:
        #        hbm2ddl.auto: update
        #        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
#          region.factory_class: org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory
#          provider_configuration_file_resource_path : hibernate-redis.properties
#          region_prefix: hibernate
#          use_structured_entries: true
#        generate_statistics: true
#      redisson-config: classpath:redisson.yaml
#      redis:
#        expiryInSeconds:
#          default: 120
#          hibernate:
#            common: 0
#            account: 1200
logging:
  level: debug
  config:


#开发环境开启swagger ，注意生成环境设置为false ，不然可以直接通过api更改环境数据
swagger:
  enable: true
flyway:
  enabled: true
  encoding: utf-8
  locations: classpath:db/migration
  table: schemas_version
  baseline-on-migrate: true
  validate-on-migrate: false


# 关闭Ribbon的重试机制（如果有必要）
ribbon:
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 5000
  ConnectTimeout: 5000


## tx-manager 配置
tx-lcn:
  client:
    manager-address: 192.168.0.223:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
