server:
  # 服务器http端口
  port: 14443
  tomcat:
    max-connections: 500
  max-http-header-size: 8192
#  # tomcat 配置
#  tomcat:
#    # 最大线程数
#    max-threads: 6
#    # 最小线程数
#    min-spare-threads: 3
#    # 队列长度
#    accept-count: 1000
#    # 最大连接数
#    max-connections: 1000
#  # 连接建立超时时间
#  connection-timeout: 10000

info:
  app.name: message-nimipro
  company.name: www.dhcc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: message-nimipro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #UTC:全球时间,Asia/Shanghai:上海时间,GMT%2B8:北京时间
    # 本地服务器
    url: jdbc:mysql://localhost:3306/dhcplat_zjzwfwzx?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    sqlSchema:
      plat: dhcplat_zjzwfwzx
#    url: jdbc:mysql://106.53.77.17:3306/dhcplat?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: dh888888
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    properties:
      hibernate:
#        hbm2ddl.auto: update
#        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
#          region.factory_class: org.hibernate.cache.redis.hibernate5.SingletonRedisRegionFactory
#          provider_configuration_file_resource_path : hibernate-redis.properties
#          region_prefix: hibernate
#          use_structured_entries: true
#        generate_statistics: true
logging:
  level: debug

#开发环境开启swagger ，注意生成环境设置为false ，不然可以直接通过api更改环境数据
swagger:
  enable: true

flyway:
  enabled: false

#启用shutdown
#禁用密码验证
endpoints:
  shutdown:
    enabled: true
    sensitive: false

cors:
# origins: http://10.254.1.106:14445,http://10.254.35.100:14445,https://servicewechat.com
# 允许所有域使用
  origins: '*'

devMode: true

token:
#  whitelist: /.*
  whitelist: /sendMessageApi/.*;

smb:
  ip: 192.168.100.79
  user: admin
  password: 123456
  path: smb://192.168.100.79


wechat:
  wechatToken: wechatToken
  appId: wx419a354d9fd6dd2f
  secret: 4dfc3f5beb9155fdd128b50d29183330
  externalTitle: 公众服务
  externalDesc: 政务服务大厅
  internalTitle: 内部服务
  internalDesc: 政务服务大厅
  mode: test
  test-secret-list:
    - Xcy9aujnpioqs00JC/kCVjiecMXO3wuZQr+AhoYc57Q1QF/HDMtH5o26IpYKDEcD0BhHWvjLdr2P0zyXDePivw==
    - j1lMmWQnMomva48sHvf126qzdx8/yt9v1P5xdVZkecrzkQUDFYee6mx7T0WXF6z9WcpbkN02SGDABIiRZktnjQ==
    - EKRYFTTqEnsyB279lXm/ADBZhiBg/4UqkyCyimWkgUwKUC5/QxDjPN69J9mD5w6kl/adz+hdnuftcIOkN7cljQ==
  # 访问腾讯接口
  userLoginUrl: https://api.weixin.qq.com/sns/jscode2session
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  sendSubscribeUrl: https://api.weixin.qq.com/cgi-bin/message/subscribe/send
  templateListUrl: https://api.weixin.qq.com/wxaapi/newtmpl/gettemplate
  facial-recognition-url: https://api.weixin.qq.com/cityservice/face/identify/getinfo